services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - "gcp:/root/.config/"
    entrypoint: gcloud

  dev:
    build:
      context: .
      target: dev
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: /bin/bash

  create_raw_encounters:
    build:
      context: .
      target: dev
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: ["pipe-encounters", "create_raw_encounters"]

  merge_encounters:
    build:
      context: .
      target: dev
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: ["pipe-encounters", "merge_encounters"]

  test:
    # Runs tests using the production Docker image.
    # Intended to be executed in the GitHub CI environment.
    build:
      context: .
      target: test
    entrypoint: "pytest -v"

volumes:
  gcp:
    external: True

